// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXooDUhaXYJak7kYWBR9DJAr475IS9IZ8',
    appId: '1:501181434655:web:5ed7c2ea290d3c27ccfe2a',
    messagingSenderId: '501181434655',
    projectId: 'shamssgazaa',
    authDomain: 'shamssgazaa.firebaseapp.com',
    storageBucket: 'shamssgazaa.appspot.com',
    measurementId: 'G-VT9KT70CW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF4Ga2OXpH_NyX3Q8hEKXmJ_Vf--jDFLc',
    appId: '1:501181434655:android:9a4c3edc121238f9ccfe2a',
    messagingSenderId: '501181434655',
    projectId: 'shamssgazaa',
    storageBucket: 'shamssgazaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgeZZeZjCbzmjkzcgMYtlsD_Lr2Lzwf7E',
    appId: '1:501181434655:ios:d4d4369bc0d66f07ccfe2a',
    messagingSenderId: '501181434655',
    projectId: 'shamssgazaa',
    storageBucket: 'shamssgazaa.appspot.com',
    iosBundleId: 'com.example.hankammelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgeZZeZjCbzmjkzcgMYtlsD_Lr2Lzwf7E',
    appId: '1:501181434655:ios:d4d4369bc0d66f07ccfe2a',
    messagingSenderId: '501181434655',
    projectId: 'shamssgazaa',
    storageBucket: 'shamssgazaa.appspot.com',
    iosBundleId: 'com.example.hankammelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXooDUhaXYJak7kYWBR9DJAr475IS9IZ8',
    appId: '1:501181434655:web:cb8e24a7ac9b567accfe2a',
    messagingSenderId: '501181434655',
    projectId: 'shamssgazaa',
    authDomain: 'shamssgazaa.firebaseapp.com',
    storageBucket: 'shamssgazaa.appspot.com',
    measurementId: 'G-KND4MG6TF5',
  );
}
